package com.greenenergy.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * HourlyElectricity is responsible for electricity generated by a Panel in an hour.
 *
 * @author javad talebi
 */
@Data
@Entity
@Table(name = "hourly_electricity")
@NoArgsConstructor
@AllArgsConstructor
public class HourlyElectricity implements Serializable {

  private static final long serialVersionUID = -575347909928592140L;
  
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;
  
  @JsonIgnore
  @ManyToOne
  @JoinColumn(name = "panel_id", referencedColumnName = "id")
  private Panel panel;
  
  @Column(name = "generated_electricity")
  private Long generatedElectricity;
  
  @Column(name = "reading_at")
  private LocalDateTime readingAt;


}
