package com.greenenergy.services;

import com.greenenergy.model.HourlyElectricity;
import com.greenenergy.model.Panel;
import com.greenenergy.repository.HourlyElectricityRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;

/**
 * HourlyElectricityServiceImpl will handle electricity generated by a Panel.
 */
@Service
public class HourlyElectricityServiceImpl implements HourlyElectricityService {

    private final HourlyElectricityRepository hourlyElectricityRepository;
    private final PanelService panelService;

    public HourlyElectricityServiceImpl(final HourlyElectricityRepository hourlyElectricityRepository,
                                        final PanelService panelService) {
        this.hourlyElectricityRepository = hourlyElectricityRepository;
        this.panelService = panelService;
    }

    @Override
    public HourlyElectricity save(HourlyElectricity hourlyElectricity, String panelSerial) {
        Panel panel = panelService.getBySerial(panelSerial);
        hourlyElectricity.setPanel(panel);

        return hourlyElectricityRepository.save(hourlyElectricity);
    }

    @Override
    public Page<HourlyElectricity> getAllHourlyElectricityByPanelId(String panelSerial, Pageable pageable) {
        Panel panel = panelService.getBySerial(panelSerial);
        return hourlyElectricityRepository.findAllByPanelId(panel.getId(), pageable);
    }

    @Override
    public List<HourlyElectricity> getAllHourlyElectricityByReadingAtBetween(LocalDateTime initialReadingAt, LocalDateTime finalReadingAt, Panel panel) {
        return this.hourlyElectricityRepository.findByReadingAtBetweenAndPanel(initialReadingAt, finalReadingAt, panel);
    }

}